# Generated by Django 6.0.6 on 2026-06-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findhosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='isFree',
            field=models.BooleanField(default=False),
        ),
    ]
