# Generated by Django 6.0.6 on 2026-06-04 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findhosts', '0002_hostel_isfree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='isFree',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='photo',
        ),
        migrations.AddField(
            model_name='hostel',
            name='total_rooms',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending - Pay at hostel'), ('confirmed', 'Confirmed - Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='findhosts.hostel')),
            ],
        ),
    ]
